version: '2'

volumes:
  cache:
    driver: local

services:
  app:
    image: 'yumeinaruu/iis:v1'
    build:
      context: .
    container_name: integrated_system
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - iis_network

  db:
    image: 'postgres:16.1'
    container_name: frosty_ride
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - iis_network
  redis:
    image: 'redis:latest'
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - iis_network


networks:
  iis_network:
    driver: bridge
